<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [

                'name' => 'Afghanistan',
                'code' => 'AF',
                'phone_code' => '93',
                'currency' => 'AFN',
                'currency_symbol' => '؋',
                'flag' => 'https://cdn.countryflags.com/thumbs/afghanistan/flag-400.png',

            ],
            [
                'name' => 'Albania',
                'code' => 'AL',
                'phone_code' => '355',
                'currency' => 'ALL',
                'currency_symbol' => 'Lek',
                'flag' => 'https://cdn.countryflags.com/thumbs/albania/flag-400.png',

            ],
            [
                'name' => 'Algeria',
                'code' => 'DZ',
                'phone_code' => '213',
                'currency' => 'DZD',
                'currency_symbol' => 'د.ج',
                'flag' => 'https://cdn.countryflags.com/thumbs/algeria/flag-400.png',

            ],
            [
                'name' => 'American Samoa',
                'code' => 'AS',
                'phone_code' => '1',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/american-samoa/flag-400.png',
            ],
            [
                'name' => 'Andorra',
                'code' => 'AD',
                'phone_code' => '376',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/andorra/flag-400.png',

            ],
            [
                'name' => 'Angola',
                'code' => 'AO',
                'phone_code' => '244',
                'currency' => 'AOA',
                'currency_symbol' => 'Kz',
                'flag' => 'https://cdn.countryflags.com/thumbs/angola/flag-400.png',

            ],
            [
                'name' => 'Anguilla',
                'code' => 'AI',
                'phone_code' => '1',
                'currency' => 'XCD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/anguilla/flag-400.png',

            ],
            [
                'name' => 'Antigua and Barbuda',
                'code' => 'AG',
                'phone_code' => '1',
                'currency' => 'XCD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/antigua-and-barbuda/flag-400.png',
            ],
            [
                'name' => 'Argentina',
                'code' => 'AR',
                'phone_code' => '54',
                'currency' => 'ARS',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/argentina/flag-400.png',
            ],
            [
                'name' => 'Armenia',
                'code' => 'AM',
                'phone_code' => '374',
                'currency' => 'AMD',
                'currency_symbol' => '֏',
                'flag' => 'https://cdn.countryflags.com/thumbs/armenia/flag-400.png',
            ],
            [
                'name' => 'Aruba',
                'code' => 'AW',
                'phone_code' => '297',
                'currency' => 'AWG',
                'currency_symbol' => 'ƒ',
                'flag' => 'https://cdn.countryflags.com/thumbs/aruba/flag-400.png',
            ],
            [
                'name' => 'Australia',
                'code' => 'AU',
                'phone_code' => '61',
                'currency' => 'AUD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/australia/flag-400.png',
            ],
            [
                'name' => 'Austria',
                'code' => 'AT',
                'phone_code' => '43',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/austria/flag-400.png',

            ],
            [
                'name' => 'Azerbaijan',
                'code' => 'AZ',
                'phone_code' => '994',
                'currency' => 'AZN',
                'currency_symbol' => '₼',
                'flag' => 'https://cdn.countryflags.com/thumbs/azerbaijan/flag-400.png',

            ],
            [
                'name' => 'Bahamas',
                'code' => 'BS',
                'phone_code' => '1',
                'currency' => 'BSD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/bahamas/flag-400.png',
            ],
            [
                'name' => 'Bahrain',
                'code' => 'BH',
                'phone_code' => '973',
                'currency' => 'BHD',
                'currency_symbol' => '.د.ب',
                'flag' => 'https://cdn.countryflags.com/thumbs/bahrain/flag-400.png',
            ],
            [
                'name' => 'Bangladesh',
                'code' => 'BD',
                'phone_code' => '880',
                'currency' => 'BDT',
                'currency_symbol' => '৳',
                'flag' => 'https://cdn.countryflags.com/thumbs/bangladesh/flag-400.png',
            ],
            [
                'name' => 'Barbados',
                'code' => 'BB',
                'phone_code' => '1',
                'currency' => 'BBD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/barbados/flag-400.png',
            ],
            [
                'name' => 'Belarus',
                'code' => 'BY',
                'phone_code' => '375',
                'currency' => 'BYN',
                'currency_symbol' => 'Br',
                'flag' => 'https://cdn.countryflags.com/thumbs/belarus/flag-400.png',
            ],
            [
                'name' => 'Belgium',
                'code' => 'BE',
                'phone_code' => '32',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/belgium/flag-400.png',

            ],
            [
                'name' => 'Belize',
                'code' => 'BZ',
                'phone_code' => '501',
                'currency' => 'BZD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/belize/flag-400.png',
            ],
            [
                'name' => 'Benin',
                'code' => 'BJ',
                'phone_code' => '229',
                'currency' => 'XOF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/benin/flag-400.png',
            ],
            [
                'name' => 'Bermuda',
                'code' => 'BM',
                'phone_code' => '1',
                'currency' => 'BMD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/bermuda/flag-400.png',
            ],
            [
                'name' => 'Bhutan',
                'code' => 'BT',
                'phone_code' => '975',
                'currency' => 'BTN',
                'currency_symbol' => 'Nu.',
                'flag' => 'https://cdn.countryflags.com/thumbs/bhutan/flag-400.png',
            ],
            [
                'name' => 'Bolivia',
                'code' => 'BO',
                'phone_code' => '591',
                'currency' => 'BOB',
                'currency_symbol' => 'Bs.',
                'flag' => 'https://cdn.countryflags.com/thumbs/bolivia/flag-400.png',

            ],
            [
                'name' => 'Bosnia and Herzegovina',
                'code' => 'BA',
                'phone_code' => '387',
                'currency' => 'BAM',
                'currency_symbol' => 'KM',
                'flag' => 'https://cdn.countryflags.com/thumbs/bosnia-and-herzegovina/flag-400.png',

            ],
            [
                'name' => 'Botswana',
                'code' => 'BW',
                'phone_code' => '267',
                'currency' => 'BWP',
                'currency_symbol' => 'P',
                'flag' => 'https://cdn.countryflags.com/thumbs/botswana/flag-400.png',
            ],
            [
                'name' => 'Brazil',
                'code' => 'BR',
                'phone_code' => '55',
                'currency' => 'BRL',
                'currency_symbol' => 'R$',
                'flag' => 'https://cdn.countryflags.com/thumbs/brazil/flag-400.png',
            ],
            [
                'name' => 'British Indian Ocean Territory',
                'code' => 'IO',
                'phone_code' => '246',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/british-indian-ocean-territory/flag-400.png',
            ],
            [
                'name' => 'British Virgin Islands',
                'code' => 'VG',
                'phone_code' => '1',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/british-virgin-islands/flag-400.png',
            ],
            [
                'name' => 'Brunei',
                'code' => 'BN',
                'phone_code' => '673',
                'currency' => 'BND',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/brunei/flag-400.png',
            ],
            [
                'name' => 'Bulgaria',
                'code' => 'BG',
                'phone_code' => '359',
                'currency' => 'BGN',
                'currency_symbol' => 'лв',
                'flag' => 'https://cdn.countryflags.com/thumbs/bulgaria/flag-400.png',
            ],
            [
                'name' => 'Burkina Faso',
                'code' => 'BF',
                'phone_code' => '226',
                'currency' => 'XOF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/burkina-faso/flag-400.png',

            ],
            [
                'name' => 'Burundi',
                'code' => 'BI',
                'phone_code' => '257',
                'currency' => 'BIF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/burundi/flag-400.png',
            ],
            [
                'name' => 'Cambodia',
                'code' => 'KH',
                'phone_code' => '855',
                'currency' => 'KHR',
                'currency_symbol' => '៛',
                'flag' => 'https://cdn.countryflags.com/thumbs/cambodia/flag-400.png',
            ],
            [
                'name' => 'Cameroon',
                'code' => 'CM',
                'phone_code' => '237',
                'currency' => 'XAF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/cameroon/flag-400.png',
            ],
            [
                'name' => 'Canada',
                'code' => 'CA',
                'phone_code' => '1',
                'currency' => 'CAD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/canada/flag-400.png',
            ],
            [
                'name' => 'Cape Verde',
                'code' => 'CV',
                'phone_code' => '238',
                'currency' => 'CVE',
                'currency_symbol' => 'Esc',
                'flag' => 'https://cdn.countryflags.com/thumbs/cape-verde/flag-400.png',
            ],
            [
                'name' => 'Cayman Islands',
                'code' => 'KY',
                'phone_code' => '1',
                'currency' => 'KYD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/cayman-islands/flag-400.png',
            ],
            [
                'name' => 'Central African Republic',
                'code' => 'CF',
                'phone_code' => '236',
                'currency' => 'XAF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/central-african-republic/flag-400.png',
            ],
            [
                'name' => 'Chad',
                'code' => 'TD',
                'phone_code' => '235',
                'currency' => 'XAF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/chad/flag-400.png',
            ],
            [
                'name' => 'Chile',
                'code' => 'CL',
                'phone_code' => '56',
                'currency' => 'CLP',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/chile/flag-400.png',
            ],
            [
                'name' => 'China',
                'code' => 'CN',
                'phone_code' => '86',
                'currency' => 'CNY',
                'currency_symbol' => '¥',
                'flag' => 'https://cdn.countryflags.com/thumbs/china/flag-400.png',
            ],
            [
                'name' => 'Christmas Island',
                'code' => 'CX',
                'phone_code' => '61',
                'currency' => 'AUD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/christmas-island/flag-400.png',
            ],
            [
                'name' => 'Cocos Islands',
                'code' => 'CC',
                'phone_code' => '61',
                'currency' => 'AUD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/cocos-islands/flag-400.png',
            ],
            [
                'name' => 'Colombia',
                'code' => 'CO',
                'phone_code' => '57',
                'currency' => 'COP',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/colombia/flag-400.png',
            ],
            [
                'name' => 'Comoros',
                'code' => 'KM',
                'phone_code' => '269',
                'currency' => 'KMF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/comoros/flag-400.png',
            ],
            [
                'name' => 'Cook Islands',
                'code' => 'CK',
                'phone_code' => '682',
                'currency' => 'NZD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/cook-islands/flag-400.png',
            ],
            [
                'name' => 'Costa Rica',
                'code' => 'CR',
                'phone_code' => '506',
                'currency' => 'CRC',
                'currency_symbol' => '₡',
                'flag' => 'https://cdn.countryflags.com/thumbs/costa-rica/flag-400.png',
            ],
            [
                'name' => 'Croatia',
                'code' => 'HR',
                'phone_code' => '385',
                'currency' => 'HRK',
                'currency_symbol' => 'kn',
                'flag' => 'https://cdn.countryflags.com/thumbs/croatia/flag-400.png',
            ],
            [
                'name' => 'Cuba',
                'code' => 'CU',
                'phone_code' => '53',
                'currency' => 'CUP',
                'currency_symbol' => '₱',
                'flag' => 'https://cdn.countryflags.com/thumbs/cuba/flag-400.png',
            ],
            [
                'name' => 'Curacao',
                'code' => 'CW',
                'phone_code' => '599',
                'currency' => 'ANG',
                'currency_symbol' => 'ƒ',
                'flag' => 'https://cdn.countryflags.com/thumbs/curacao/flag-400.png',
            ],
            [
                'name' => 'Cyprus',
                'code' => 'CY',
                'phone_code' => '357',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/cyprus/flag-400.png',
            ],
            [
                'name' => 'Czech Republic',
                'code' => 'CZ',
                'phone_code' => '420',
                'currency' => 'CZK',
                'currency_symbol' => 'Kč',
                'flag' => 'https://cdn.countryflags.com/thumbs/czech-republic/flag-400.png',
            ],
            [
                'name' => 'Democratic Republic of the Congo',
                'code' => 'CD',
                'phone_code' => '243',
                'currency' => 'CDF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/democratic-republic-of-the-congo/flag-400.png',
            ],
            [
                'name' => 'Denmark',
                'code' => 'DK',
                'phone_code' => '45',
                'currency' => 'DKK',
                'currency_symbol' => 'kr',
                'flag' => 'https://cdn.countryflags.com/thumbs/denmark/flag-400.png',
            ],
            [
                'name' => 'Djibouti',
                'code' => 'DJ',
                'phone_code' => '253',
                'currency' => 'DJF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/djibouti/flag-400.png',
            ],
            [
                'name' => 'Dominica',
                'code' => 'DM',
                'phone_code' => '1',
                'currency' => 'XCD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/dominica/flag-400.png',
            ],
            [
                'name' => 'Dominican Republic',
                'code' => 'DO',
                'phone_code' => '1',
                'currency' => 'DOP',
                'currency_symbol' => 'RD$',
                'flag' => 'https://cdn.countryflags.com/thumbs/dominican-republic/flag-400.png',
            ],
            [
                'name' => 'East Timor',
                'code' => 'TL',
                'phone_code' => '670',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/east-timor/flag-400.png',
            ],
            [
                'name' => 'Ecuador',
                'code' => 'EC',
                'phone_code' => '593',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/ecuador/flag-400.png',
            ],
            [
                'name' => 'Egypt',
                'code' => 'EG',
                'phone_code' => '20',
                'currency' => 'EGP',
                'currency_symbol' => '£',
                'flag' => 'https://cdn.countryflags.com/thumbs/egypt/flag-400.png',
            ],
            [
                'name' => 'El Salvador',
                'code' => 'SV',
                'phone_code' => '503',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/el-salvador/flag-400.png',
            ],
            [
                'name' => 'Equatorial Guinea',
                'code' => 'GQ',
                'phone_code' => '240',
                'currency' => 'XAF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/equatorial-guinea/flag-400.png',
            ],
            [
                'name' => 'Eritrea',
                'code' => 'ER',
                'phone_code' => '291',
                'currency' => 'ERN',
                'currency_symbol' => 'Nfk',
                'flag' => 'https://cdn.countryflags.com/thumbs/eritrea/flag-400.png',
            ],
            [
                'name' => 'Estonia',
                'code' => 'EE',
                'phone_code' => '372',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/estonia/flag-400.png',
            ],
            [
                'name' => 'Ethiopia',
                'code' => 'ET',
                'phone_code' => '251',
                'currency' => 'ETB',
                'currency_symbol' => 'Br',
                'flag' => 'https://cdn.countryflags.com/thumbs/ethiopia/flag-400.png',
            ],
            [
                'name' => 'Falkland Islands',
                'code' => 'FK',
                'phone_code' => '500',
                'currency' => 'FKP',
                'currency_symbol' => '£',
                'flag' => 'https://cdn.countryflags.com/thumbs/falkland-islands/flag-400.png',
            ],
            [
                'name' => 'Faroe Islands',
                'code' => 'FO',
                'phone_code' => '298',
                'currency' => 'DKK',
                'currency_symbol' => 'kr',
                'flag' => 'https://cdn.countryflags.com/thumbs/faroe-islands/flag-400.png',
            ],
            [
                'name' => 'Fiji',
                'code' => 'FJ',
                'phone_code' => '679',
                'currency' => 'FJD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/fiji/flag-400.png',
            ],
            [
                'name' => 'Finland',
                'code' => 'FI',
                'phone_code' => '358',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/finland/flag-400.png',
            ],
            [
                'name' => 'France',
                'code' => 'FR',
                'phone_code' => '33',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/france/flag-400.png',
            ],
            [
                'name' => 'French Polynesia',
                'code' => 'PF',
                'phone_code' => '689',
                'currency' => 'XPF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/french-polynesia/flag-400.png',
            ],
            [
                'name' => 'Gabon',
                'code' => 'GA',
                'phone_code' => '241',
                'currency' => 'XAF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/gabon/flag-400.png',
            ],
            [
                'name' => 'Gambia',
                'code' => 'GM',
                'phone_code' => '220',
                'currency' => 'GMD',
                'currency_symbol' => 'D',
                'flag' => 'https://cdn.countryflags.com/thumbs/gambia/flag-400.png',
            ],
            [
                'name' => 'Georgia',
                'code' => 'GE',
                'phone_code' => '995',
                'currency' => 'GEL',
                'currency_symbol' => 'ლ',
                'flag' => 'https://cdn.countryflags.com/thumbs/georgia/flag-400.png',
            ],
            [
                'name' => 'Germany',
                'code' => 'DE',
                'phone_code' => '49',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/germany/flag-400.png',
            ],
            [
                'name' => 'Ghana',
                'code' => 'GH',
                'phone_code' => '233',
                'currency' => 'GHS',
                'currency_symbol' => '₵',
                'flag' => 'https://cdn.countryflags.com/thumbs/ghana/flag-400.png',
            ],
            [
                'name' => 'Gibraltar',
                'code' => 'GI',
                'phone_code' => '350',
                'currency' => 'GIP',
                'currency_symbol' => '£',
                'flag' => 'https://cdn.countryflags.com/thumbs/gibraltar/flag-400.png',
            ],
            [
                'name' => 'Greece',
                'code' => 'GR',
                'phone_code' => '30',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/greece/flag-400.png',
            ],
            [
                'name' => 'Greenland',
                'code' => 'GL',
                'phone_code' => '299',
                'currency' => 'DKK',
                'currency_symbol' => 'kr',
                'flag' => 'https://cdn.countryflags.com/thumbs/greenland/flag-400.png',
            ],
            [
                'name' => 'Grenada',
                'code' => 'GD',
                'phone_code' => '1',
                'currency' => 'XCD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/grenada/flag-400.png',
            ],
            [
                'name' => 'Guam',
                'code' => 'GU',
                'phone_code' => '1',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/guam/flag-400.png',
            ],
            [
                'name' => 'Guatemala',
                'code' => 'GT',
                'phone_code' => '502',
                'currency' => 'GTQ',
                'currency_symbol' => 'Q',
                'flag' => 'https://cdn.countryflags.com/thumbs/guatemala/flag-400.png',
            ],
            [
                'name' => 'Guernsey',
                'code' => 'GG',
                'phone_code' => '44',
                'currency' => 'GBP',
                'currency_symbol' => '£',
                'flag' => 'https://cdn.countryflags.com/thumbs/guernsey/flag-400.png',
            ],
            [
                'name' => 'Guinea',
                'code' => 'GN',
                'phone_code' => '224',
                'currency' => 'GNF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/guinea/flag-400.png',
            ],
            [
                'name' => 'Guinea-Bissau',
                'code' => 'GW',
                'phone_code' => '245',
                'currency' => 'XOF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/guinea-bissau/flag-400.png',
            ],
            [
                'name' => 'Guyana',
                'code' => 'GY',
                'phone_code' => '592',
                'currency' => 'GYD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/guyana/flag-400.png',
            ],
            [
                'name' => 'Haiti',
                'code' => 'HT',
                'phone_code' => '509',
                'currency' => 'HTG',
                'currency_symbol' => 'G',
                'flag' => 'https://cdn.countryflags.com/thumbs/haiti/flag-400.png',
            ],
            [
                'name' => 'Honduras',
                'code' => 'HN',
                'phone_code' => '504',
                'currency' => 'HNL',
                'currency_symbol' => 'L',
                'flag' => 'https://cdn.countryflags.com/thumbs/honduras/flag-400.png',
            ],
            [
                'name' => 'Hong Kong',
                'code' => 'HK',
                'phone_code' => '852',
                'currency' => 'HKD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/hong-kong/flag-400.png',
            ],
            [
                'name' => 'Hungary',
                'code' => 'HU',
                'phone_code' => '36',
                'currency' => 'HUF',
                'currency_symbol' => 'Ft',
                'flag' => 'https://cdn.countryflags.com/thumbs/hungary/flag-400.png',
            ],
            [
                'name' => 'Iceland',
                'code' => 'IS',
                'phone_code' => '354',
                'currency' => 'ISK',
                'currency_symbol' => 'kr',
                'flag' => 'https://cdn.countryflags.com/thumbs/iceland/flag-400.png',
            ],
            [
                'name' => 'India',
                'code' => 'IN',
                'phone_code' => '91',
                'currency' => 'INR',
                'currency_symbol' => '₹',
                'flag' => 'https://cdn.countryflags.com/thumbs/india/flag-400.png',
            ],
            [
                'name' => 'Indonesia',
                'code' => 'ID',
                'phone_code' => '62',
                'currency' => 'IDR',
                'currency_symbol' => 'Rp',
                'flag' => 'https://cdn.countryflags.com/thumbs/indonesia/flag-400.png',
            ],
            [
                'name' => 'Iran',
                'code' => 'IR',
                'phone_code' => '98',
                'currency' => 'IRR',
                'currency_symbol' => '﷼',
                'flag' => 'https://cdn.countryflags.com/thumbs/iran/flag-400.png',
            ],
            [
                'name' => 'Iraq',
                'code' => 'IQ',
                'phone_code' => '964',
                'currency' => 'IQD',
                'currency_symbol' => 'ع.د',
                'flag' => 'https://cdn.countryflags.com/thumbs/iraq/flag-400.png',
            ],
            [
                'name' => 'Ireland',
                'code' => 'IE',
                'phone_code' => '353',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/ireland/flag-400.png',
            ],
            [
                'name' => 'Israel',
                'code' => 'IL',
                'phone_code' => '972',
                'currency' => 'ILS',
                'currency_symbol' => '₪',
                'flag' => 'https://cdn.countryflags.com/thumbs/israel/flag-400.png',
            ],
            [
                'name' => 'Italy',
                'code' => 'IT',
                'phone_code' => '39',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/italy/flag-400.png',
            ],
            [
                'name' => 'Ivory Coast',
                'code' => 'CI',
                'phone_code' => '225',
                'currency' => 'XOF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/ivory-coast/flag-400.png',
            ],
            [
                'name' => 'Jamaica',
                'code' => 'JM',
                'phone_code' => '1',
                'currency' => 'JMD',
                'currency_symbol' => 'J$',
                'flag' => 'https://cdn.countryflags.com/thumbs/jamaica/flag-400.png',
            ],
            [
                'name' => 'Japan',
                'code' => 'JP',
                'phone_code' => '81',
                'currency' => 'JPY',
                'currency_symbol' => '¥',
                'flag' => 'https://cdn.countryflags.com/thumbs/japan/flag-400.png',
            ],
            [
                'name' => 'Jersey',
                'code' => 'JE',
                'phone_code' => '44',
                'currency' => 'GBP',
                'currency_symbol' => '£',
                'flag' => 'https://cdn.countryflags.com/thumbs/jersey/flag-400.png',
            ],
            [
                'name' => 'Jordan',
                'code' => 'JO',
                'phone_code' => '962',
                'currency' => 'JOD',
                'currency_symbol' => 'د.ا',
                'flag' => 'https://cdn.countryflags.com/thumbs/jordan/flag-400.png',
            ],
            [
                'name' => 'Kazakhstan',
                'code' => 'KZ',
                'phone_code' => '7',
                'currency' => 'KZT',
                'currency_symbol' => 'лв',
                'flag' => 'https://cdn.countryflags.com/thumbs/kazakhstan/flag-400.png',
            ],
            [
                'name' => 'Kenya',
                'code' => 'KE',
                'phone_code' => '254',
                'currency' => 'KES',
                'currency_symbol' => 'KSh',
                'flag' => 'https://cdn.countryflags.com/thumbs/kenya/flag-400.png',
            ],
            [
                'name' => 'Kiribati',
                'code' => 'KI',
                'phone_code' => '686',
                'currency' => 'AUD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/kiribati/flag-400.png',
            ],
            [
                'name' => 'Kosovo',
                'code' => 'XK',
                'phone_code' => '383',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/kosovo/flag-400.png',
            ],
            [
                'name' => 'Kuwait',
                'code' => 'KW',
                'phone_code' => '965',
                'currency' => 'KWD',
                'currency_symbol' => 'د.ك',
                'flag' => 'https://cdn.countryflags.com/thumbs/kuwait/flag-400.png',
            ],
            [
                'name' => 'Kyrgyzstan',
                'code' => 'KG',
                'phone_code' => '996',
                'currency' => 'KGS',
                'currency_symbol' => 'лв',
                'flag' => 'https://cdn.countryflags.com/thumbs/kyrgyzstan/flag-400.png',
            ],
            [
                'name' => 'Laos',
                'code' => 'LA',
                'phone_code' => '856',
                'currency' => 'LAK',
                'currency_symbol' => '₭',
                'flag' => 'https://cdn.countryflags.com/thumbs/laos/flag-400.png',
            ],
            [
                'name' => 'Latvia',
                'code' => 'LV',
                'phone_code' => '371',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/latvia/flag-400.png',
            ],
            [
                'name' => 'Lebanon',
                'code' => 'LB',
                'phone_code' => '961',
                'currency' => 'LBP',
                'currency_symbol' => 'ل.ل',
                'flag' => 'https://cdn.countryflags.com/thumbs/lebanon/flag-400.png',
            ],
            [
                'name' => 'Lesotho',
                'code' => 'LS',
                'phone_code' => '266',
                'currency' => 'LSL',
                'currency_symbol' => 'L',
                'flag' => 'https://cdn.countryflags.com/thumbs/lesotho/flag-400.png',
            ],
            [
                'name' => 'Liberia',
                'code' => 'LR',
                'phone_code' => '231',
                'currency' => 'LRD',
                'currency_symbol' => 'L$',
                'flag' => 'https://cdn.countryflags.com/thumbs/liberia/flag-400.png',
            ],
            [
                'name' => 'Libya',
                'code' => 'LY',
                'phone_code' => '218',
                'currency' => 'LYD',
                'currency_symbol' => 'ل.د',
                'flag' => 'https://cdn.countryflags.com/thumbs/libya/flag-400.png',
            ],
            [
                'name' => 'Liechtenstein',
                'code' => 'LI',
                'phone_code' => '423',
                'currency' => 'CHF',
                'currency_symbol' => 'CHF',
                'flag' => 'https://cdn.countryflags.com/thumbs/liechtenstein/flag-400.png',
            ],
            [
                'name' => 'Lithuania',
                'code' => 'LT',
                'phone_code' => '370',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/lithuania/flag-400.png',
            ],
            [
                'name' => 'Luxembourg',
                'code' => 'LU',
                'phone_code' => '352',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/luxembourg/flag-400.png',
            ],
            [
                'name' => 'Macau',
                'code' => 'MO',
                'phone_code' => '853',
                'currency' => 'MOP',
                'currency_symbol' => 'MOP',
                'flag' => 'https://cdn.countryflags.com/thumbs/macau/flag-400.png',
            ],
            [
                'name' => 'Macedonia',
                'code' => 'MK',
                'phone_code' => '389',
                'currency' => 'MKD',
                'currency_symbol' => 'ден',
                'flag' => 'https://cdn.countryflags.com/thumbs/macedonia/flag-400.png',
            ],
            [
                'name' => 'Madagascar',
                'code' => 'MG',
                'phone_code' => '261',
                'currency' => 'MGA',
                'currency_symbol' => 'Ar',
                'flag' => 'https://cdn.countryflags.com/thumbs/madagascar/flag-400.png',
            ],
            [
                'name' => 'Malawi',
                'code' => 'MW',
                'phone_code' => '265',
                'currency' => 'MWK',
                'currency_symbol' => 'MK',
                'flag' => 'https://cdn.countryflags.com/thumbs/malawi/flag-400.png',
            ],
            [
                'name' => 'Malaysia',
                'code' => 'MY',
                'phone_code' => '60',
                'currency' => 'MYR',
                'currency_symbol' => 'RM',
                'flag' => 'https://cdn.countryflags.com/thumbs/malaysia/flag-400.png',
            ],
            [
                'name' => 'Maldives',
                'code' => 'MV',
                'phone_code' => '960',
                'currency' => 'MVR',
                'currency_symbol' => 'MVR',
                'flag' => 'https://cdn.countryflags.com/thumbs/maldives/flag-400.png',
            ],
            [
                'name' => 'Mali',
                'code' => 'ML',
                'phone_code' => '223',
                'currency' => 'XOF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/mali/flag-400.png',
            ],
            [
                'name' => 'Malta',
                'code' => 'MT',
                'phone_code' => '356',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/malta/flag-400.png',
            ],
            [
                'name' => 'Marshall Islands',
                'code' => 'MH',
                'phone_code' => '692',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/marshall-islands/flag-400.png',
            ],
            [
                'name' => 'Mauritania',
                'code' => 'MR',
                'phone_code' => '222',
                'currency' => 'MRO',
                'currency_symbol' => 'UM',
                'flag' => 'https://cdn.countryflags.com/thumbs/mauritania/flag-400.png',
            ],
            [
                'name' => 'Mauritius',
                'code' => 'MU',
                'phone_code' => '230',
                'currency' => 'MUR',
                'currency_symbol' => '₨',
                'flag' => 'https://cdn.countryflags.com/thumbs/mauritius/flag-400.png',
            ],
            [
                'name' => 'Mayotte',
                'code' => 'YT',
                'phone_code' => '262',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/mayotte/flag-400.png',
            ],
            [
                'name' => 'Mexico',
                'code' => 'MX',
                'phone_code' => '52',
                'currency' => 'MXN',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/mexico/flag-400.png',
            ],
            [
                'name' => 'Micronesia',
                'code' => 'FM',
                'phone_code' => '691',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/micronesia/flag-400.png',
            ],
            [
                'name' => 'Moldova',
                'code' => 'MD',
                'phone_code' => '373',
                'currency' => 'MDL',
                'currency_symbol' => 'L',
                'flag' => 'https://cdn.countryflags.com/thumbs/moldova/flag-400.png',
            ],
            [
                'name' => 'Monaco',
                'code' => 'MC',
                'phone_code' => '377',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/monaco/flag-400.png',
            ],
            [
                'name' => 'Mongolia',
                'code' => 'MN',
                'phone_code' => '976',
                'currency' => 'MNT',
                'currency_symbol' => '₮',
                'flag' => 'https://cdn.countryflags.com/thumbs/mongolia/flag-400.png',
            ],
            [
                'name' => 'Montenegro',
                'code' => 'ME',
                'phone_code' => '382',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/montenegro/flag-400.png',
            ],
            [
                'name' => 'Montserrat',
                'code' => 'MS',
                'phone_code' => '1',
                'currency' => 'XCD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/montserrat/flag-400.png',
            ],
            [
                'name' => 'Morocco',
                'code' => 'MA',
                'phone_code' => '212',
                'currency' => 'MAD',
                'currency_symbol' => 'د.م.',
                'flag' => 'https://cdn.countryflags.com/thumbs/morocco/flag-400.png',
            ],
            [
                'name' => 'Mozambique',
                'code' => 'MZ',
                'phone_code' => '258',
                'currency' => 'MZN',
                'currency_symbol' => 'MT',
                'flag' => 'https://cdn.countryflags.com/thumbs/mozambique/flag-400.png',
            ],
            [
                'name' => 'Myanmar',
                'code' => 'MM',
                'phone_code' => '95',
                'currency' => 'MMK',
                'currency_symbol' => 'K',
                'flag' => 'https://cdn.countryflags.com/thumbs/myanmar/flag-400.png',
            ],
            [
                'name' => 'Namibia',
                'code' => 'NA',
                'phone_code' => '264',
                'currency' => 'NAD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/namibia/flag-400.png',
            ],
            [
                'name' => 'Nauru',
                'code' => 'NR',
                'phone_code' => '674',
                'currency' => 'AUD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/nauru/flag-400.png',
            ],
            [
                'name' => 'Nepal',
                'code' => 'NP',
                'phone_code' => '977',
                'currency' => 'NPR',
                'currency_symbol' => '₨',
                'flag' => 'https://cdn.countryflags.com/thumbs/nepal/flag-400.png',
            ],
            [
                'name' => 'Netherlands',
                'code' => 'NL',
                'phone_code' => '31',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/netherlands/flag-400.png',
            ],
            [
                'name' => 'Netherlands Antilles',
                'code' => 'AN',
                'phone_code' => '599',
                'currency' => 'ANG',
                'currency_symbol' => 'ƒ',
                'flag' => 'https://cdn.countryflags.com/thumbs/netherlands-antilles/flag-400.png',
            ], [
                'name' => 'New Caledonia',
                'code' => 'NC',
                'phone_code' => '687',
                'currency' => 'XPF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/new-caledonia/flag-400.png',
            ], [
                'name' => 'New Zealand',
                'code' => 'NZ',
                'phone_code' => '64',
                'currency' => 'NZD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/new-zealand/flag-400.png',
            ], [
                'name' => 'Nicaragua',
                'code' => 'NI',
                'phone_code' => '505',
                'currency' => 'NIO',
                'currency_symbol' => 'C$',
                'flag' => 'https://cdn.countryflags.com/thumbs/nicaragua/flag-400.png',
            ], [
                'name' => 'Niger',
                'code' => 'NE',
                'phone_code' => '227',
                'currency' => 'XOF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/niger/flag-400.png',
            ], [
                'name' => 'Nigeria',
                'code' => 'NG',
                'phone_code' => '234',
                'currency' => 'NGN',
                'currency_symbol' => '₦',
                'flag' => 'https://cdn.countryflags.com/thumbs/nigeria/flag-400.png',
            ], [
                'name' => 'Niue',
                'code' => 'NU',
                'phone_code' => '683',
                'currency' => 'NZD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/niue/flag-400.png',
            ], [
                'name' => 'Norfolk Island',
                'code' => 'NF',
                'phone_code' => '672',
                'currency' => 'AUD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/norfolk-island/flag-400.png',
            ], [
                'name' => 'North Korea',
                'code' => 'KP',
                'phone_code' => '850',
                'currency' => 'KPW',
                'currency_symbol' => '₩',
                'flag' => 'https://cdn.countryflags.com/thumbs/north-korea/flag-400.png',
            ], [
                'name' => 'Northern Mariana Islands',
                'code' => 'MP',
                'phone_code' => '1',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/northern-mariana-islands/flag-400.png',
            ], [
                'name' => 'Norway',
                'code' => 'NO',
                'phone_code' => '47',
                'currency' => 'NOK',
                'currency_symbol' => 'kr',
                'flag' => 'https://cdn.countryflags.com/thumbs/norway/flag-400.png',
            ], [
                'name' => 'Oman',
                'code' => 'OM',
                'phone_code' => '968',
                'currency' => 'OMR',
                'currency_symbol' => '﷼',
                'flag' => 'https://cdn.countryflags.com/thumbs/oman/flag-400.png',
            ], [
                'name' => 'Pakistan',
                'code' => 'PK',
                'phone_code' => '92',
                'currency' => 'PKR',
                'currency_symbol' => '₨',
                'flag' => 'https://cdn.countryflags.com/thumbs/pakistan/flag-400.png',
            ], [
                'name' => 'Palau',
                'code' => 'PW',
                'phone_code' => '680',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/palau/flag-400.png',

            ],
            [
                'name' => 'Panama',
                'code' => 'PA',
                'phone_code' => '507',
                'currency' => 'PAB',
                'currency_symbol' => 'B/.',
                'flag' => 'https://cdn.countryflags.com/thumbs/panama/flag-400.png',
            ], [
                'name' => 'Papua New Guinea',
                'code' => 'PG',
                'phone_code' => '675',
                'currency' => 'PGK',
                'currency_symbol' => 'K',
                'flag' => 'https://cdn.countryflags.com/thumbs/papua-new-guinea/flag-400.png',
            ], [
                'name' => 'Paraguay',
                'code' => 'PY',
                'phone_code' => '595',
                'currency' => 'PYG',
                'currency_symbol' => '₲',
                'flag' => 'https://cdn.countryflags.com/thumbs/paraguay/flag-400.png',
            ], [
                'name' => 'Peru',
                'code' => 'PE',
                'phone_code' => '51',
                'currency' => 'PEN',
                'currency_symbol' => 'S/.',
                'flag' => 'https://cdn.countryflags.com/thumbs/peru/flag-400.png',
            ], [
                'name' => 'Philippines',
                'code' => 'PH',
                'phone_code' => '63',
                'currency' => 'PHP',
                'currency_symbol' => '₱',
                'flag' => 'https://cdn.countryflags.com/thumbs/philippines/flag-400.png',
            ], [
                'name' => 'Pitcairn',
                'code' => 'PN',
                'phone_code' => '64',
                'currency' => 'NZD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/pitcairn-islands/flag-400.png',
            ], [
                'name' => 'Poland',
                'code' => 'PL',
                'phone_code' => '48',
                'currency' => 'PLN',
                'currency_symbol' => 'zł',
                'flag' => 'https://cdn.countryflags.com/thumbs/poland/flag-400.png',
            ], [
                'name' => 'Portugal',
                'code' => 'PT',
                'phone_code' => '351',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/portugal/flag-400.png',
            ], [
                'name' => 'Puerto Rico',
                'code' => 'PR',
                'phone_code' => '1',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/puerto-rico/flag-400.png',
            ], [
                'name' => 'Qatar',
                'code' => 'QA',
                'phone_code' => '974',
                'currency' => 'QAR',
                'currency_symbol' => '﷼',
                'flag' => 'https://cdn.countryflags.com/thumbs/qatar/flag-400.png',
            ], [
                'name' => 'Republic of the Congo',
                'code' => 'CG',
                'phone_code' => '242',
                'currency' => 'XAF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/republic-of-the-congo/flag-400.png',
            ], [
                'name' => 'Reunion',
                'code' => 'RE',
                'phone_code' => '262',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/reunion/flag-400.png',
            ], [
                'name' => 'Romania',
                'code' => 'RO',
                'phone_code' => '40',
                'currency' => 'RON',
                'currency_symbol' => 'lei',
                'flag' => 'https://cdn.countryflags.com/thumbs/romania/flag-400.png',
            ], [
                'name' => 'Russia',
                'code' => 'RU',
                'phone_code' => '7',
                'currency' => 'RUB',
                'currency_symbol' => 'руб',
                'flag' => 'https://cdn.countryflags.com/thumbs/russia/flag-400.png',
            ],
            [
                'name' => 'Rwanda',
                'code' => 'RW',
                'phone_code' => '250',
                'currency' => 'RWF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/rwanda/flag-400.png',
            ],
            [
                'name' => 'Saint Barthelemy',
                'code' => 'BL',
                'phone_code' => '590',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/saint-barthelemy/flag-400.png',
            ], [
                'name' => 'Saint Helena',
                'code' => 'SH',
                'phone_code' => '290',
                'currency' => 'SHP',
                'currency_symbol' => '£',
                'flag' => 'https://cdn.countryflags.com/thumbs/saint-helena/flag-400.png',
            ], [
                'name' => 'Saint Kitts and Nevis',
                'code' => 'KN',
                'phone_code' => '1',
                'currency' => 'XCD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/saint-kitts-and-nevis/flag-400.png',
            ], [
                'name' => 'Saint Lucia',
                'code' => 'LC',
                'phone_code' => '1',
                'currency' => 'XCD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/saint-lucia/flag-400.png',
            ], [
                'name' => 'Saint Martin',
                'code' => 'MF',
                'phone_code' => '590',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/saint-martin/flag-400.png',
            ], [
                'name' => 'Saint Pierre and Miquelon',
                'code' => 'PM',
                'phone_code' => '508',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/saint-pierre-and-miquelon/flag-400.png',
            ], [
                'name' => 'Saint Vincent and the Grenadines',
                'code' => 'VC',
                'phone_code' => '1',
                'currency' => 'XCD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/saint-vincent-and-the-grenadines/flag-400.png',
            ], [
                'name' => 'Samoa',
                'code' => 'WS',
                'phone_code' => '685',
                'currency' => 'WST',
                'currency_symbol' => 'T',
                'flag' => 'https://cdn.countryflags.com/thumbs/samoa/flag-400.png',
            ], [
                'name' => 'San Marino',
                'code' => 'SM',
                'phone_code' => '378',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/san-marino/flag-400.png',
            ], [
                'name' => 'Sao Tome and Principe',
                'code' => 'ST',
                'phone_code' => '239',
                'currency' => 'STD',
                'currency_symbol' => 'Db',
                'flag' => 'https://cdn.countryflags.com/thumbs/sao-tome-and-principe/flag-400.png',
            ], [
                'name' => 'Saudi Arabia',
                'code' => 'SA',
                'phone_code' => '966',

                'currency' => 'SAR',
                'currency_symbol' => '﷼',
                'flag' => 'https://cdn.countryflags.com/thumbs/saudi-arabia/flag-400.png',
            ], [
                'name' => 'Senegal',
                'code' => 'SN',
                'phone_code' => '221',
                'currency' => 'XOF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/senegal/flag-400.png',
            ], [
                'name' => 'Serbia',
                'code' => 'RS',
                'phone_code' => '381',
                'currency' => 'RSD',
                'currency_symbol' => 'Дин.',
                'flag' => 'https://cdn.countryflags.com/thumbs/serbia/flag-400.png',
            ], [
                'name' => 'Seychelles',
                'code' => 'SC',
                'phone_code' => '248',
                'currency' => 'SCR',
                'currency_symbol' => '₨',
                'flag' => 'https://cdn.countryflags.com/thumbs/seychelles/flag-400.png',
            ], [
                'name' => 'Sierra Leone',
                'code' => 'SL',
                'phone_code' => '232',
                'currency' => 'SLL',
                'currency_symbol' => 'Le',
                'flag' => 'https://cdn.countryflags.com/thumbs/sierra-leone/flag-400.png',
            ], [
                'name' => 'Singapore',
                'code' => 'SG',
                'phone_code' => '65',
                'currency' => 'SGD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/singapore/flag-400.png',
            ], [
                'name' => 'Sint Maarten',
                'code' => 'SX',
                'phone_code' => '1',
                'currency' => 'ANG',
                'currency_symbol' => 'ƒ',
                'flag' => 'https://cdn.countryflags.com/thumbs/sint-maarten/flag-400.png',
            ], [
                'name' => 'Slovakia',
                'code' => 'SK',
                'phone_code' => '421',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/slovakia/flag-400.png',
            ], [
                'name' => 'Slovenia',
                'code' => 'SI',
                'phone_code' => '386',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/slovenia/flag-400.png',
            ], [
                'name' => 'Solomon Islands',
                'code' => 'SB',
                'phone_code' => '677',
                'currency' => 'SBD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/solomon-islands/flag-400.png',
            ], [
                'name' => 'Somalia',
                'code' => 'SO',
                'phone_code' => '252',
                'currency' => 'SOS',
                'currency_symbol' => 'S',
                'flag' => 'https://cdn.countryflags.com/thumbs/somalia/flag-400.png',
            ], [
                'name' => 'South Africa',
                'code' => 'ZA',
                'phone_code' => '27',
                'currency' => 'ZAR',
                'currency_symbol' => 'R',
                'flag' => 'https://cdn.countryflags.com/thumbs/south-africa/flag-400.png',
            ], [
                'name' => 'South Korea',
                'code' => 'KR',
                'phone_code' => '82',
                'currency' => 'KRW',
                'currency_symbol' => '₩',
                'flag' => 'https://cdn.countryflags.com/thumbs/south-korea/flag-400.png',
            ], [
                'name' => 'South Sudan',
                'code' => 'SS',
                'phone_code' => '211',
                'currency' => 'SSP',
                'currency_symbol' => '£',
                'flag' => 'https://cdn.countryflags.com/thumbs/south-sudan/flag-400.png',
            ], [
                'name' => 'Spain',
                'code' => 'ES',
                'phone_code' => '34',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/spain/flag-400.png',
            ], [
                'name' => 'Sri Lanka',
                'code' => 'LK',
                'phone_code' => '94',
                'currency' => 'LKR',
                'currency_symbol' => '₨',
                'flag' => 'https://cdn.countryflags.com/thumbs/sri-lanka/flag-400.png',
            ], [
                'name' => 'Sudan',
                'code' => 'SD',
                'phone_code' => '249',
                'currency' => 'SDG',
                'currency_symbol' => 'ج.س.',
                'flag' => 'https://cdn.countryflags.com/thumbs/sudan/flag-400.png',
            ], [
                'name' => 'Suriname',
                'code' => 'SR',
                'phone_code' => '597',
                'currency' => 'SRD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/suriname/flag-400.png',
            ], [
                'name' => 'Svalbard and Jan Mayen',
                'code' => 'SJ',
                'phone_code' => '47',
                'currency' => 'NOK',
                'currency_symbol' => 'kr',
                'flag' => 'https://cdn.countryflags.com/thumbs/svalbard-and-jan-mayen/flag-400.png',
            ], [
                'name' => 'Swaziland',
                'code' => 'SZ',
                'phone_code' => '268',
                'currency' => 'SZL',
                'currency_symbol' => 'L',
                'flag' => 'https://cdn.countryflags.com/thumbs/swaziland/flag-400.png',
            ], [
                'name' => 'Sweden',
                'code' => 'SE',
                'phone_code' => '46',
                'currency' => 'SEK',
                'currency_symbol' => 'kr',
                'flag' => 'https://cdn.countryflags.com/thumbs/sweden/flag-400.png',
            ], [
                'name' => 'Switzerland',
                'code' => 'CH',
                'phone_code' => '41',
                'currency' => 'CHF',
                'currency_symbol' => 'CHF',
                'flag' => 'https://cdn.countryflags.com/thumbs/switzerland/flag-400.png',
            ], [
                'name' => 'Syria',
                'code' => 'SY',
                'phone_code' => '963',
                'currency' => 'SYP',
                'currency_symbol' => '£',
                'flag' => 'https://cdn.countryflags.com/thumbs/syria/flag-400.png',
            ], [
                'name' => 'Taiwan',
                'code' => 'TW',
                'phone_code' => '886',
                'currency' => 'TWD',
                'currency_symbol' => 'NT$',
                'flag' => 'https://cdn.countryflags.com/thumbs/taiwan/flag-400.png',
            ], [
                'name' => 'Tajikistan',
                'code' => 'TJ',
                'phone_code' => '992',
                'currency' => 'TJS',
                'currency_symbol' => 'ЅМ',
                'flag' => 'https://cdn.countryflags.com/thumbs/tajikistan/flag-400.png',
            ], [
                'name' => 'Tanzania',
                'code' => 'TZ',
                'phone_code' => '255',
                'currency' => 'TZS',
                'currency_symbol' => 'TSh',
                'flag' => 'https://cdn.countryflags.com/thumbs/tanzania/flag-400.png',
            ], [
                'name' => 'Thailand',
                'code' => 'TH',
                'phone_code' => '66',
                'currency' => 'THB',
                'currency_symbol' => '฿',
                'flag' => 'https://cdn.countryflags.com/thumbs/thailand/flag-400.png',
            ], [
                'name' => 'Togo',
                'code' => 'TG',
                'phone_code' => '228',
                'currency' => 'XOF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/togo/flag-400.png',
            ], [
                'name' => 'Tokelau',
                'code' => 'TK',
                'phone_code' => '690',
                'currency' => 'NZD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/tokelau/flag-400.png',
            ],
            [
                'name' => 'Tonga',
                'code' => 'TO',
                'phone_code' => '676',
                'currency' => 'TOP',
                'currency_symbol' => 'T$',
                'flag' => 'https://cdn.countryflags.com/thumbs/tonga/flag-400.png',
            ],
            [
                'name' => 'Trinidad and Tobago',
                'code' => 'TT',
                'phone_code' => '1',
                'currency' => 'TTD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/trinidad-and-tobago/flag-400.png',
            ],
            [
                'name' => 'Tunisia',
                'code' => 'TN',
                'phone_code' => '216',
                'currency' => 'TND',
                'currency_symbol' => 'د.ت',
                'flag' => 'https://cdn.countryflags.com/thumbs/tunisia/flag-400.png',
            ],
            [
                'name' => 'Turkey',
                'code' => 'TR',
                'phone_code' => '90',
                'currency' => 'TRY',
                'currency_symbol' => 'Lira',
                'flag' => 'https://cdn.countryflags.com/thumbs/turkey/flag-400.png',
            ],
            [
                'name' => 'Turkmenistan',
                'code' => 'TM',
                'phone_code' => '993',
                'currency' => 'TMT',
                'currency_symbol' => 'm',
                'flag' => 'https://cdn.countryflags.com/thumbs/turkmenistan/flag-400.png',
            ],
            [
                'name' => 'Turks and Caicos Islands',
                'code' => 'TC',
                'phone_code' => '1',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/turks-and-caicos-islands/flag-400.png',
            ],
            [
                'name' => 'Tuvalu',
                'code' => 'TV',
                'phone_code' => '688',
                'currency' => 'AUD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/tuvalu/flag-400.png',
            ],
            [
                'name' => 'U.S. Virgin Islands',
                'code' => 'VI',
                'phone_code' => '1',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/virgin-islands/flag-400.png',
            ],
            [
                'name' => 'Uganda',
                'code' => 'UG',
                'phone_code' => '256',
                'currency' => 'UGX',
                'currency_symbol' => 'USh',
                'flag' => 'https://cdn.countryflags.com/thumbs/uganda/flag-400.png',
            ],
            [
                'name' => 'Ukraine',
                'code' => 'UA',
                'phone_code' => '380',
                'currency' => 'UAH',
                'currency_symbol' => '₴',
                'flag' => 'https://cdn.countryflags.com/thumbs/ukraine/flag-400.png',
            ],
            [
                'name' => 'United Arab Emirates',
                'code' => 'AE',
                'phone_code' => '971',
                'currency' => 'AED',
                'currency_symbol' => 'د.إ',
                'flag' => 'https://cdn.countryflags.com/thumbs/united-arab-emirates/flag-400.png',
            ],
            [
                'name' => 'United Kingdom',
                'code' => 'GB',
                'phone_code' => '44',
                'currency' => 'GBP',
                'currency_symbol' => '£',
                'flag' => 'https://cdn.countryflags.com/thumbs/united-kingdom/flag-400.png',
            ],
            [
                'name' => 'United States',
                'code' => 'US',
                'phone_code' => '1',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png',
            ],
            [
                'name' => 'Uruguay',
                'code' => 'UY',
                'phone_code' => '598',
                'currency' => 'UYU',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/uruguay/flag-400.png',
            ],
            [
                'name' => 'Uzbekistan',
                'code' => 'UZ',
                'phone_code' => '998',
                'currency' => 'UZS',
                'currency_symbol' => 'лв',
                'flag' => 'https://cdn.countryflags.com/thumbs/uzbekistan/flag-400.png',
            ],
            [
                'name' => 'Vanuatu',
                'code' => 'VU',
                'phone_code' => '678',
                'currency' => 'VUV',
                'currency_symbol' => 'Vt',
                'flag' => 'https://cdn.countryflags.com/thumbs/vanuatu/flag-400.png',
            ],
            [
                'name' => 'Vatican',
                'code' => 'VA',
                'phone_code' => '379',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => 'https://cdn.countryflags.com/thumbs/vatican-city/flag-400.png',
            ],
            [
                'name' => 'Venezuela',
                'code' => 'VE',
                'phone_code' => '58',
                'currency' => 'VEF',
                'currency_symbol' => 'Bs F',
                'flag' => 'https://cdn.countryflags.com/thumbs/venezuela/flag-400.png',
            ],
            [
                'name' => 'Vietnam',
                'code' => 'VN',
                'phone_code' => '84',
                'currency' => 'VND',
                'currency_symbol' => '₫',
                'flag' => 'https://cdn.countryflags.com/thumbs/vietnam/flag-400.png',
            ],
            [
                'name' => 'Wallis and Futuna',
                'code' => 'WF',
                'phone_code' => '681',
                'currency' => 'XPF',
                'currency_symbol' => 'Fr',
                'flag' => 'https://cdn.countryflags.com/thumbs/wallis-and-futuna/flag-400.png',
            ],
            [
                'name' => 'Western Sahara',
                'code' => 'EH',
                'phone_code' => '212',
                'currency' => 'MAD',
                'currency_symbol' => 'MAD',
                'flag' => 'https://cdn.countryflags.com/thumbs/western-sahara/flag-400.png',
            ],
            [
                'name' => 'Yemen',
                'code' => 'YE',
                'phone_code' => '967',
                'currency' => 'YER',
                'currency_symbol' => '﷼',
                'flag' => 'https://cdn.countryflags.com/thumbs/yemen/flag-400.png',
            ],
            [
                'name' => 'Zambia',
                'code' => 'ZM',
                'phone_code' => '260',
                'currency' => 'ZMK',
                'currency_symbol' => 'ZK',
                'flag' => 'https://cdn.countryflags.com/thumbs/zambia/flag-400.png',
            ],
            [
                'name' => 'Zimbabwe',
                'code' => 'ZW',
                'phone_code' => '263',
                'currency' => 'ZWL',
                'currency_symbol' => '$',
                'flag' => 'https://cdn.countryflags.com/thumbs/zimbabwe/flag-400.png',
            ],
        ];

        Country::insert($countries);
    }
}
